<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE training-schedule[
<!ELEMENT training-schedule (year*)>
<!ELEMENT year (month*)>
<!ATTLIST year num CDATA #REQUIRED>
<!ELEMENT month (training*)>
<!ATTLIST month num CDATA #REQUIRED>
<!ELEMENT training (client,instructor,training-date,training-type,status)>
<!ATTLIST training num CDATA #REQUIRED>
<!ELEMENT training-date (data,time)>
<!ELEMENT client (#PCDATA)>
<!ATTLIST client id CDATA #REQUIRED>
<!ELEMENT instructor (#PCDATA)>
<!ATTLIST instructor id CDATA #REQUIRED>
<!ELEMENT data (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT training-type (#PCDATA)>
<!ELEMENT status (#PCDATA)>
]>
<training-schedule>
<year num="2020">
    <month num="02">
        <training num="1">
            <client id="000567"/>
            <instructor id="000145"/>
            <training-date>
                <data>26.02.2020</data>
                <time>16:00</time>
            </training-date>
            <training-type>Обычная</training-type>
            <status>Проведена</status>
        </training>
        <training num="2">
            <client id="000568"/>
            <instructor id="000145"/>
            <training-date>
                <data>27.02.2020</data>
                <time>17:00</time>
            </training-date>
            <training-type>Обычная</training-type>
            <status>Проведена</status>
        </training>  
    </month>
    <month num="03">
        <training num="1">
            <client id="000567"/>
            <instructor id="000145"/>
            <training-date>
                <data>08.03.2020</data>
                <time>18:00</time>
            </training-date>
            <training-type>Комплексная</training-type>
            <status>Запланирована</status>
        </training>
    </month>
</year>

</training-schedule>